# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ramon/Desktop/Thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ramon/Desktop/Thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramon/Desktop/Thesis/CMakeFiles /home/ramon/Desktop/Thesis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramon/Desktop/Thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named A_Client

# Build rule for target.
A_Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 A_Client
.PHONY : A_Client

# fast build rule for target.
A_Client/fast:
	$(MAKE) -f CMakeFiles/A_Client.dir/build.make CMakeFiles/A_Client.dir/build
.PHONY : A_Client/fast

#=============================================================================
# Target rules for targets named DetectionShort

# Build rule for target.
DetectionShort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DetectionShort
.PHONY : DetectionShort

# fast build rule for target.
DetectionShort/fast:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/build
.PHONY : DetectionShort/fast

#=============================================================================
# Target rules for targets named Detection

# Build rule for target.
Detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Detection
.PHONY : Detection

# fast build rule for target.
Detection/fast:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/build
.PHONY : Detection/fast

#=============================================================================
# Target rules for targets named T_Client

# Build rule for target.
T_Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T_Client
.PHONY : T_Client

# fast build rule for target.
T_Client/fast:
	$(MAKE) -f CMakeFiles/T_Client.dir/build.make CMakeFiles/T_Client.dir/build
.PHONY : T_Client/fast

#=============================================================================
# Target rules for targets named S_Client

# Build rule for target.
S_Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 S_Client
.PHONY : S_Client

# fast build rule for target.
S_Client/fast:
	$(MAKE) -f CMakeFiles/S_Client.dir/build.make CMakeFiles/S_Client.dir/build
.PHONY : S_Client/fast

#=============================================================================
# Target rules for targets named A_Server2

# Build rule for target.
A_Server2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 A_Server2
.PHONY : A_Server2

# fast build rule for target.
A_Server2/fast:
	$(MAKE) -f CMakeFiles/A_Server2.dir/build.make CMakeFiles/A_Server2.dir/build
.PHONY : A_Server2/fast

#=============================================================================
# Target rules for targets named T_Server

# Build rule for target.
T_Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T_Server
.PHONY : T_Server

# fast build rule for target.
T_Server/fast:
	$(MAKE) -f CMakeFiles/T_Server.dir/build.make CMakeFiles/T_Server.dir/build
.PHONY : T_Server/fast

#=============================================================================
# Target rules for targets named S_Server

# Build rule for target.
S_Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 S_Server
.PHONY : S_Server

# fast build rule for target.
S_Server/fast:
	$(MAKE) -f CMakeFiles/S_Server.dir/build.make CMakeFiles/S_Server.dir/build
.PHONY : S_Server/fast

#=============================================================================
# Target rules for targets named A_Server

# Build rule for target.
A_Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 A_Server
.PHONY : A_Server

# fast build rule for target.
A_Server/fast:
	$(MAKE) -f CMakeFiles/A_Server.dir/build.make CMakeFiles/A_Server.dir/build
.PHONY : A_Server/fast

ASynchronous/client.o: ASynchronous/client.cpp.o

.PHONY : ASynchronous/client.o

# target to build an object file
ASynchronous/client.cpp.o:
	$(MAKE) -f CMakeFiles/A_Client.dir/build.make CMakeFiles/A_Client.dir/ASynchronous/client.cpp.o
.PHONY : ASynchronous/client.cpp.o

ASynchronous/client.i: ASynchronous/client.cpp.i

.PHONY : ASynchronous/client.i

# target to preprocess a source file
ASynchronous/client.cpp.i:
	$(MAKE) -f CMakeFiles/A_Client.dir/build.make CMakeFiles/A_Client.dir/ASynchronous/client.cpp.i
.PHONY : ASynchronous/client.cpp.i

ASynchronous/client.s: ASynchronous/client.cpp.s

.PHONY : ASynchronous/client.s

# target to generate assembly for a file
ASynchronous/client.cpp.s:
	$(MAKE) -f CMakeFiles/A_Client.dir/build.make CMakeFiles/A_Client.dir/ASynchronous/client.cpp.s
.PHONY : ASynchronous/client.cpp.s

ASynchronous/server.o: ASynchronous/server.cpp.o

.PHONY : ASynchronous/server.o

# target to build an object file
ASynchronous/server.cpp.o:
	$(MAKE) -f CMakeFiles/A_Server.dir/build.make CMakeFiles/A_Server.dir/ASynchronous/server.cpp.o
.PHONY : ASynchronous/server.cpp.o

ASynchronous/server.i: ASynchronous/server.cpp.i

.PHONY : ASynchronous/server.i

# target to preprocess a source file
ASynchronous/server.cpp.i:
	$(MAKE) -f CMakeFiles/A_Server.dir/build.make CMakeFiles/A_Server.dir/ASynchronous/server.cpp.i
.PHONY : ASynchronous/server.cpp.i

ASynchronous/server.s: ASynchronous/server.cpp.s

.PHONY : ASynchronous/server.s

# target to generate assembly for a file
ASynchronous/server.cpp.s:
	$(MAKE) -f CMakeFiles/A_Server.dir/build.make CMakeFiles/A_Server.dir/ASynchronous/server.cpp.s
.PHONY : ASynchronous/server.cpp.s

ASynchronous/server2.o: ASynchronous/server2.cpp.o

.PHONY : ASynchronous/server2.o

# target to build an object file
ASynchronous/server2.cpp.o:
	$(MAKE) -f CMakeFiles/A_Server2.dir/build.make CMakeFiles/A_Server2.dir/ASynchronous/server2.cpp.o
.PHONY : ASynchronous/server2.cpp.o

ASynchronous/server2.i: ASynchronous/server2.cpp.i

.PHONY : ASynchronous/server2.i

# target to preprocess a source file
ASynchronous/server2.cpp.i:
	$(MAKE) -f CMakeFiles/A_Server2.dir/build.make CMakeFiles/A_Server2.dir/ASynchronous/server2.cpp.i
.PHONY : ASynchronous/server2.cpp.i

ASynchronous/server2.s: ASynchronous/server2.cpp.s

.PHONY : ASynchronous/server2.s

# target to generate assembly for a file
ASynchronous/server2.cpp.s:
	$(MAKE) -f CMakeFiles/A_Server2.dir/build.make CMakeFiles/A_Server2.dir/ASynchronous/server2.cpp.s
.PHONY : ASynchronous/server2.cpp.s

SimpleDetection/detection.o: SimpleDetection/detection.cpp.o

.PHONY : SimpleDetection/detection.o

# target to build an object file
SimpleDetection/detection.cpp.o:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/SimpleDetection/detection.cpp.o
.PHONY : SimpleDetection/detection.cpp.o

SimpleDetection/detection.i: SimpleDetection/detection.cpp.i

.PHONY : SimpleDetection/detection.i

# target to preprocess a source file
SimpleDetection/detection.cpp.i:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/SimpleDetection/detection.cpp.i
.PHONY : SimpleDetection/detection.cpp.i

SimpleDetection/detection.s: SimpleDetection/detection.cpp.s

.PHONY : SimpleDetection/detection.s

# target to generate assembly for a file
SimpleDetection/detection.cpp.s:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/SimpleDetection/detection.cpp.s
.PHONY : SimpleDetection/detection.cpp.s

SimpleDetection/detectionShort.o: SimpleDetection/detectionShort.cpp.o

.PHONY : SimpleDetection/detectionShort.o

# target to build an object file
SimpleDetection/detectionShort.cpp.o:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/SimpleDetection/detectionShort.cpp.o
.PHONY : SimpleDetection/detectionShort.cpp.o

SimpleDetection/detectionShort.i: SimpleDetection/detectionShort.cpp.i

.PHONY : SimpleDetection/detectionShort.i

# target to preprocess a source file
SimpleDetection/detectionShort.cpp.i:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/SimpleDetection/detectionShort.cpp.i
.PHONY : SimpleDetection/detectionShort.cpp.i

SimpleDetection/detectionShort.s: SimpleDetection/detectionShort.cpp.s

.PHONY : SimpleDetection/detectionShort.s

# target to generate assembly for a file
SimpleDetection/detectionShort.cpp.s:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/SimpleDetection/detectionShort.cpp.s
.PHONY : SimpleDetection/detectionShort.cpp.s

Synchronous/client.o: Synchronous/client.cpp.o

.PHONY : Synchronous/client.o

# target to build an object file
Synchronous/client.cpp.o:
	$(MAKE) -f CMakeFiles/S_Client.dir/build.make CMakeFiles/S_Client.dir/Synchronous/client.cpp.o
.PHONY : Synchronous/client.cpp.o

Synchronous/client.i: Synchronous/client.cpp.i

.PHONY : Synchronous/client.i

# target to preprocess a source file
Synchronous/client.cpp.i:
	$(MAKE) -f CMakeFiles/S_Client.dir/build.make CMakeFiles/S_Client.dir/Synchronous/client.cpp.i
.PHONY : Synchronous/client.cpp.i

Synchronous/client.s: Synchronous/client.cpp.s

.PHONY : Synchronous/client.s

# target to generate assembly for a file
Synchronous/client.cpp.s:
	$(MAKE) -f CMakeFiles/S_Client.dir/build.make CMakeFiles/S_Client.dir/Synchronous/client.cpp.s
.PHONY : Synchronous/client.cpp.s

Synchronous/server.o: Synchronous/server.cpp.o

.PHONY : Synchronous/server.o

# target to build an object file
Synchronous/server.cpp.o:
	$(MAKE) -f CMakeFiles/S_Server.dir/build.make CMakeFiles/S_Server.dir/Synchronous/server.cpp.o
.PHONY : Synchronous/server.cpp.o

Synchronous/server.i: Synchronous/server.cpp.i

.PHONY : Synchronous/server.i

# target to preprocess a source file
Synchronous/server.cpp.i:
	$(MAKE) -f CMakeFiles/S_Server.dir/build.make CMakeFiles/S_Server.dir/Synchronous/server.cpp.i
.PHONY : Synchronous/server.cpp.i

Synchronous/server.s: Synchronous/server.cpp.s

.PHONY : Synchronous/server.s

# target to generate assembly for a file
Synchronous/server.cpp.s:
	$(MAKE) -f CMakeFiles/S_Server.dir/build.make CMakeFiles/S_Server.dir/Synchronous/server.cpp.s
.PHONY : Synchronous/server.cpp.s

test/client.o: test/client.cpp.o

.PHONY : test/client.o

# target to build an object file
test/client.cpp.o:
	$(MAKE) -f CMakeFiles/T_Client.dir/build.make CMakeFiles/T_Client.dir/test/client.cpp.o
.PHONY : test/client.cpp.o

test/client.i: test/client.cpp.i

.PHONY : test/client.i

# target to preprocess a source file
test/client.cpp.i:
	$(MAKE) -f CMakeFiles/T_Client.dir/build.make CMakeFiles/T_Client.dir/test/client.cpp.i
.PHONY : test/client.cpp.i

test/client.s: test/client.cpp.s

.PHONY : test/client.s

# target to generate assembly for a file
test/client.cpp.s:
	$(MAKE) -f CMakeFiles/T_Client.dir/build.make CMakeFiles/T_Client.dir/test/client.cpp.s
.PHONY : test/client.cpp.s

test/server.o: test/server.cpp.o

.PHONY : test/server.o

# target to build an object file
test/server.cpp.o:
	$(MAKE) -f CMakeFiles/T_Server.dir/build.make CMakeFiles/T_Server.dir/test/server.cpp.o
.PHONY : test/server.cpp.o

test/server.i: test/server.cpp.i

.PHONY : test/server.i

# target to preprocess a source file
test/server.cpp.i:
	$(MAKE) -f CMakeFiles/T_Server.dir/build.make CMakeFiles/T_Server.dir/test/server.cpp.i
.PHONY : test/server.cpp.i

test/server.s: test/server.cpp.s

.PHONY : test/server.s

# target to generate assembly for a file
test/server.cpp.s:
	$(MAKE) -f CMakeFiles/T_Server.dir/build.make CMakeFiles/T_Server.dir/test/server.cpp.s
.PHONY : test/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... A_Client"
	@echo "... DetectionShort"
	@echo "... Detection"
	@echo "... T_Client"
	@echo "... S_Client"
	@echo "... edit_cache"
	@echo "... A_Server2"
	@echo "... T_Server"
	@echo "... S_Server"
	@echo "... A_Server"
	@echo "... ASynchronous/client.o"
	@echo "... ASynchronous/client.i"
	@echo "... ASynchronous/client.s"
	@echo "... ASynchronous/server.o"
	@echo "... ASynchronous/server.i"
	@echo "... ASynchronous/server.s"
	@echo "... ASynchronous/server2.o"
	@echo "... ASynchronous/server2.i"
	@echo "... ASynchronous/server2.s"
	@echo "... SimpleDetection/detection.o"
	@echo "... SimpleDetection/detection.i"
	@echo "... SimpleDetection/detection.s"
	@echo "... SimpleDetection/detectionShort.o"
	@echo "... SimpleDetection/detectionShort.i"
	@echo "... SimpleDetection/detectionShort.s"
	@echo "... Synchronous/client.o"
	@echo "... Synchronous/client.i"
	@echo "... Synchronous/client.s"
	@echo "... Synchronous/server.o"
	@echo "... Synchronous/server.i"
	@echo "... Synchronous/server.s"
	@echo "... test/client.o"
	@echo "... test/client.i"
	@echo "... test/client.s"
	@echo "... test/server.o"
	@echo "... test/server.i"
	@echo "... test/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

