# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ramon/Desktop/Thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ramon/Desktop/Thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramon/Desktop/Thesis/CMakeFiles /home/ramon/Desktop/Thesis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramon/Desktop/Thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Detection

# Build rule for target.
Detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Detection
.PHONY : Detection

# fast build rule for target.
Detection/fast:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/build
.PHONY : Detection/fast

#=============================================================================
# Target rules for targets named DetectionShort

# Build rule for target.
DetectionShort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DetectionShort
.PHONY : DetectionShort

# fast build rule for target.
DetectionShort/fast:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/build
.PHONY : DetectionShort/fast

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client.cpp.s
.PHONY : client.cpp.s

detection.o: detection.cpp.o

.PHONY : detection.o

# target to build an object file
detection.cpp.o:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/detection.cpp.o
.PHONY : detection.cpp.o

detection.i: detection.cpp.i

.PHONY : detection.i

# target to preprocess a source file
detection.cpp.i:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/detection.cpp.i
.PHONY : detection.cpp.i

detection.s: detection.cpp.s

.PHONY : detection.s

# target to generate assembly for a file
detection.cpp.s:
	$(MAKE) -f CMakeFiles/Detection.dir/build.make CMakeFiles/Detection.dir/detection.cpp.s
.PHONY : detection.cpp.s

detectionShort.o: detectionShort.cpp.o

.PHONY : detectionShort.o

# target to build an object file
detectionShort.cpp.o:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/detectionShort.cpp.o
.PHONY : detectionShort.cpp.o

detectionShort.i: detectionShort.cpp.i

.PHONY : detectionShort.i

# target to preprocess a source file
detectionShort.cpp.i:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/detectionShort.cpp.i
.PHONY : detectionShort.cpp.i

detectionShort.s: detectionShort.cpp.s

.PHONY : detectionShort.s

# target to generate assembly for a file
detectionShort.cpp.s:
	$(MAKE) -f CMakeFiles/DetectionShort.dir/build.make CMakeFiles/DetectionShort.dir/detectionShort.cpp.s
.PHONY : detectionShort.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Client"
	@echo "... edit_cache"
	@echo "... Server"
	@echo "... Detection"
	@echo "... DetectionShort"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... detection.o"
	@echo "... detection.i"
	@echo "... detection.s"
	@echo "... detectionShort.o"
	@echo "... detectionShort.i"
	@echo "... detectionShort.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

